/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java Library project to get you started.
 * For more details take a look at the Java Libraries chapter in the Gradle
 * User Manual available at https://docs.gradle.org/5.6.4/userguide/java_library_plugin.html
 */

repositories {
    // Use jcenter for resolving dependencies.
    // You can declare any Maven/Ivy/file repository here.
    google()
    jcenter()
    mavenCentral()
}

plugins {
    // Apply the application plugin to add support for Main class
    application

    // Apply the java-library plugin to add support for Java Library
    `java-library`
}

application {
    mainClassName = "app.btcore.java.MainApplication"
}

dependencies {
    // This dependency is exported to consumers, that is to say found on their compile classpath.
    api("org.apache.commons:commons-math3:3.6.1")

    // This dependency is used internally, and not exposed to consumers on their own compile classpath.
    implementation("com.google.guava:guava:28.0-jre")

    // We use GSON for serialization
    implementation("com.google.code.gson:gson:2.8.6")

    // We use Retrofit for our HTTP requests
    compile("com.squareup.okhttp3:okhttp:3.14.4")
    implementation("com.squareup.retrofit2:retrofit:2.6.2") {
        exclude(module = "okhttp")
    }
    implementation("com.squareup.retrofit2:converter-gson:2.6.2") {
        exclude(module = "gson")
    }

    // Use JUnit test framework
    testImplementation("junit:junit:4.12")
}


tasks {
    test {
        testLogging {
          showStandardStreams = true
        }
    }
}
